config/routes.rb
Yelp::Application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  get "restaurant/index"
  get "homepage/index"

  root "homepage#index"
  resources :charges
  resources :restaurants do 
    resources :reviews 
  end

  

end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base

  has_many :reviews

  geocoded_by :address
  after_validation :geocode 

  def average
    reviews.map(&:rating).inject(&:+) / reviews.count unless reviews.count == 0
  end
  
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :restaurant

  after_save :send_owner_email

  def send_owner_email
    return if restaurant.owner_email.empty?
    mail = ReviewMailer.notify_owner(restaurant.owner_email, self)
    mail.deliver
  end
end

app/models/user.rb
class User < ActiveRecord::Base

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable

  def self.find_for_facebook_oauth(auth, signed_in_resource=nil)
    user = User.where(:provider => auth.provider, :uid => auth.uid).first
    if user
      return user
    else
      registered_user = User.where(:email => auth.info.email).first
      if registered_user
        return registered_user
      else
        user = User.create( provider:auth.provider,
                            uid:auth.uid,
                            email:auth.info.email,
                            password:Devise.friendly_token[0,20],
                          )
      end
       
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  # helper_method :average

  # def average
  # end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

  def new
  end

  def create
    # Amount in cents
    @amount = 500

    customer = Stripe::Customer.create(
      :email => 'example@stripe.com',
      :card  => params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      :customer    => customer.id,
      :amount      => @amount,
      :description => 'Rails Stripe customer',
      :currency    => 'usd'
    )

  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to charges_path
  end


end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  def index
    @restaurants = Restaurant.all
    @hash = Gmaps4rails.build_markers(@restaurants) do |restaurant, marker|
      marker.lat restaurant.latitude
      marker.lng restaurant.longitude
      marker.infowindow restaurant.name
    end
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  before_action :authenticate_user!, except: :index

  def index
    @restaurants = Restaurant.all
    @hash = Gmaps4rails.build_markers(@restaurants) do |restaurant, marker|
      marker.lat restaurant.latitude
      marker.lng restaurant.longitude
      marker.infowindow restaurant.name
    end
  end

  def new 
  end

  def destroy 
    @restaurant = Restaurant.find(params[:id])
    @restaurant.destroy 

    redirect_to '/'
  end

  def update
    @restaurant = Restaurant.find(params[:id])

    if @restaurant.update(params[:restaurant].permit(:name, :description, :latitude, :longitude, :address, :owner_email))
      redirect_to @restaurant 
    else 
      render 'edit'
    end
  end

  def edit
    @restaurant = Restaurant.find(params[:id])
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    @restaurant.save 
    redirect_to @restaurant
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end



  private 
    def restaurant_params
      params.require(:restaurant).permit(:name, :description, :latitude, :longitude, :address, :owner_email)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  before_action :authenticate_user!, except: :index
  
  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = @restaurant.reviews.create(params[:review].permit(:comment, :rating))
    redirect_to restaurant_path(@restaurant)
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.find_for_facebook_oauth(request.env["omniauth.auth"], current_user)
 
    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper

end

app/helpers/restaurant_helper.rb
module RestaurantHelper

end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/charges/create.html.erb
<h2>Thanks, you paid <strong>$5.00</strong>!</h2>

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
  <article>
    <label class="amount">
      <span>Amount: $5.00</span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="A month's subscription"
          data-amount="500"></script>
<% end %>

app/views/homepage/index.html.erb
<% @restaurants.each do |restaurant| %>
  <div class="wrapper">
    <div class="wrapper-restaurant">
      <p class="restaurant-name">
        <strong><%= link_to restaurant.name, restaurant %></strong>
      </p>
      <p>
        <%= restaurant.description %>
      </p>
      <p>
        <h6>
          Average Customer Rating:
        </h6>
          <span class="stars average">
              <%= restaurant.average %>
          </span>
      </p>
      <span class="update-delete"><%= link_to "Edit", edit_restaurant_path(restaurant) %></span>
      <span class="update-delete"><%= link_to "Delete", restaurant_path(restaurant), method: :delete, data: { confirm: 'Are you sure?'} %></span>
      <button href="#collapse<%= restaurant.id %>" class="show-comments">Show Comments</button>
    </div>
    <div class="comments" id="collapse<%= restaurant.id %>" style="display:none">
      <h5>Comments</h5>
      <% restaurant.reviews.each do |review| %>
        <%= review.comment %>
        <span class="stars"><%= review.rating %></span>
      <% end %>
     </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Yelp" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
    <script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
    <script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>
  </head>
  <body>

    <div class="navbar navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">Yelp</a>
        <a class="navbar-brand functions add-rest" href="/restaurants">+ Add Restaurants</a>
        <a class="navbar-brand functions signing" href="/users/sign_up">Sign Up</a>
        <a class="navbar-brand functions" href="/users/sign_in">Sign In</a>
        <%= link_to "Sign in with Facebook", user_omniauth_authorize_path(:facebook) %>
        <a data-method="delete" class="navbar-brand functions" href="/users/sign_out">Sign Out</a>
        <div class="nav-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Link1", "/path1"  %></li>
            <li><%= link_to "Link2", "/path2"  %></li>
            <li><%= link_to "Link3", "/path3"  %></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <!-- <div id="map-canvas"></div> -->
          <%= bootstrap_flash %>
          <div class="google-maps" style='width: 350px;'>
          <div id="map" style='width: 350px; height: 200px;'></div>
          </div>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2013</p>
      </footer>


    </div> <!-- /container -->
  <script type="text/javascript">
  handler = Gmaps.build('Google');
  handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
  markers = handler.addMarkers(<%=raw @hash.to_json %>);
  handler.bounds.extendWith(markers);
  handler.fitMapToBounds();
});
</script>
  </body>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
<head>
</head>
<body>
  <%= yield %>
</body>
</html>

app/views/layouts/old-application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Yelp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/restaurants/edit.html.erb
<h3>Edit restaurant details</h3>

<%= form_for :restaurant, url: restaurant_path(@restaurant), method: :patch do |f| %>

  <% if @restaurant.errors.any? %>
    <div class="error-explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited
        this post from being saved:</h2>
      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>

  <p>
    <%= f.label :longitude %><br>
    <%= f.text_field :longitude %>
  </p>

  <p>
    <%= f.label :address %><br>
    <%= f.text_area :address %> 
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>
 
<%= link_to 'Back', restaurants_path %>

app/views/restaurants/index.html.erb
<%= form_for :restaurant, url: restaurants_path do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p> 

  <p> 
    <%= f.label :description %><br>
    <%= f.text_area :description %> 
  </p>

  <p>
    <%= f.label :latitude %><br>
    <%= f.text_field :latitude %>
  </p>

  <p>
    <%= f.label :longitude %><br>
    <%= f.text_field :longitude %>
  </p>

  <p>
    <%= f.label :address %><br>
    <%= f.text_field :address %> 
  </p>

  <p>
    <%= f.label :owner_email, "Owner's email" %>
    <%= f.text_field :owner_email %>
  </p>

  <p>
    <%= f.submit 'Add Restaurant', :class => 'stripe-button' %>
  </p>
  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="A month's subscription"
          data-amount="500"></script>
<% end %>

app/views/restaurants/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @restaurant.name %>
</p>

<p>
  <strong>Description</strong>
  <%= @restaurant.description %>
</p>

<%= render 'reviews/reviews' %>

<%= render 'reviews/newreview' %>

app/views/reviews/_newreview.html.erb
<h2>Add a review:</h2>
<%= form_for([@restaurant, @restaurant.reviews.build]) do |f| %>
  <p>
    <%= f.label :comment %><br />
    <%= f.text_area :comment %>
  </p>
  <p>
    <%= f.label :rating %><br />
    <%= f.select :rating, options_for_select(%w[1 2 3 4 5]) %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>
 
<%= link_to 'Back', restaurants_path %>
| <%= link_to 'Edit', edit_restaurant_path(@restaurant) %>

app/views/reviews/_reviews.html.erb
<h5>Reviews</h5>
<% @restaurant.reviews.each do |review| %>
  <p>
    <%= review.comment %>
  <p>
    <%= review.rating %> / 5
  </p>
<% end %>